const A='/game-art-review/assets/instant/';
const H=s=>'/game-art-review/instant/?section='+s;
const states=[
 ['ready','Ready on the dock','Stake and difficulty are editable. CASH OUT is unavailable. GO starts the first hop.'],
 ['jump','Jump resolving','GO, CASH OUT, stake and difficulty are locked. One request is resolving.'],
 ['active','Safe landing · 1.50×','The next target is 1.80×. GO and CASH OUT $15.00 are available on a $10.00 stake.'],
 ['cashout','Cashout complete','The displayed total return is settled once. A receipt stays visible before a new round.'],
 ['sink','Barrel sinks','The attempted barrel tips and drops. The uncashed round ends; no retry inside this round.'],
 ['shark','Shark strike','A side-entry shark interrupts the attempted landing. Same failed-step result.'],
 ['tentacle','Tentacle grab','A purple coil pulls the pirate off the attempted barrel. Same failed-step result.'],
 ['funds','Insufficient balance','Keep the entered amount and explain the error beside the stake. GO stays disabled.'],
 ['reconnecting','Reconnecting','Keep the last confirmed multiplier. Lock round actions until the result is known.']
];
const fig=(file,alt,caption='')=>`<figure class="pirate-figure"><a href="${A+file}" target="_blank" rel="noopener"><img data-study src="${A+file}" alt="${alt}" loading="lazy"></a>${caption?`<figcaption>${caption}</figcaption>`:''}</figure>`;
const table=(heads,rows)=>`<div class="pirate-table"><table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const note=t=>`<aside class="pirate-note">${t}</aside>`;
const links=()=>`<nav class="board-jumps"><a href="${H('final-ui')}">Desktop & mobile</a><a href="${H('states')}">All states</a><a href="${H('animation')}">Loss & motion</a><a href="${H('production')}">Production plan</a></nav>`;
const briefRows=[['Game','Pirate Sea Hop — working title. A forward crossing with one hop per advance.'],['Story','A cheerful pirate crosses a busy harbor using floating barrels. Each landing creates the next go-or-cash-out decision.'],['Audience hypothesis','Adults familiar with short instant-game rounds who value clear stakes, readable targets and playful visual feedback. Validate this hypothesis with adult users.'],['Visual style','Refined Nintendo 64: economical geometry, painted diffuse detail, broad shading and clear color groups.'],['Differentiation','A readable rear-view journey through water, a recognizable pirate silhouette and three comic loss performances. These are presentation differences; no new betting mechanic is claimed.'],['Core promise','The next target stays visible. Current total return and cashout stay readable independently of world animation.']];

export async function renderInstant({content,active,heading,wireDisplay}){
  document.body.classList.add('pirate-review');
  if(!document.querySelector('link[href="/game-art-review/instant-review.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/game-art-review/instant-review.css';document.head.append(l);}
  const head=(n,t,d)=>heading(n+' / INSTANT GAME',t,d);
  const display='<div class="segmented" role="group" aria-label="Art display"><button data-display="color" aria-pressed="true">Color</button><button data-display="grayscale" aria-pressed="false">Grayscale</button></div>';
  const pages={
    brief:()=>head('01','A harbor crossing, made readable.','Keep the existing instant-game decision loop. Change its world and visual expression.')+table(['Topic','Direction'],briefRows)+
      `<section><h2>The round</h2><ol class="pirate-flow"><li>Choose a stake and difficulty on the fixed dock.</li><li>GO requests one forward hop. Actions lock while it resolves.</li><li>A safe landing updates the total multiplier and cashout amount.</li><li>Choose GO again or CASH OUT.</li><li>A failed advance ends the uncashed round using one loss performance.</li></ol></section>`+
      note('<strong>Multiplier meaning:</strong> 1.50× means a total return of $15.00 on a $10.00 stake. It is not an extra $15.00 prize. The visible sequence 1.50× → 1.80× → 2.10× → 2.50× → 3.00× → 3.60× is a supplied visual fixture, not the complete game schedule or a stated maximum.')+
      `<section><h2>Keep the scope clear</h2><p>No steering, aiming, reaction test, combat, alternate routes or new bonus rules. Barrel movement and hazards illustrate a resolved outcome. They do not reveal a safe time to press GO.</p><p>Production probabilities, difficulty schedules, settlement and GO MAX behavior must come from the original game specification. This review uses scripted outcomes and demo amounts.</p></section>`,
    'art-direction':()=>head('02','Cool water. Warm wood. Clear decisions.','Use the supplied harbor and actual N64 references as the visual foundation.')+
      `<div class="section-heading"><h2>Reference and direction board</h2>${display}</div><div class="pirate-art-grid">${fig('harbor-reference.jpg','Supplied harbor background','Supplied environment · composition and color authority.')}${fig('n64-kong-frame.png','Donkey Kong N64 game frame','Supplied N64 game footage · broad shading and economical mesh reference.')}${fig('n64-bowser-frame.png','Bowser N64 game frame','Supplied N64 game footage · simple painted texture and contour reference.')}${fig('character-options.jpg','Four draft boar pirate outfits','Project character study · all four outfits remain under review.')}</div>`+
      `<section><h2>Palette and hierarchy</h2><div class="palette-grid">${[['#17BBD5','Harbor water'],['#C88A40','Warm barrel wood'],['#172D49','Navy type & coat'],['#FFF0CD','Ivory labels'],['#F57950','GO / coral'],['#57CCB5','CASH OUT / teal']].map(c=>`<div class="swatch"><div style="background:${c[0]}"></div><strong>${c[1]}</strong><code>${c[0]}</code></div>`).join('')}</div><p>Water occupies the broad field. Wood describes the route. Navy and ivory carry readable values; coral and teal separate the two primary actions. Purple is reserved for the tentacle.</p></section>`+
      `<section><h2>Rules for every asset</h2><ul class="pirate-points"><li>Large shapes and broad vertex shading; no random triangle-color patchwork.</li><li>Simple painted wood and cloth, without realistic fibers, fur or metal reflections.</li><li>Sharp live numerals and UI text, even when the art evokes low-resolution games.</li><li>Keep effects outside the next-target label and the cashout readout.</li><li>Use shape, text and state in addition to color.</li></ul></section>`,
    'character-concept':()=>head('03','A friendly pirate, still under review.','J1 is the temporary composition stand-in; no final character or outfit is selected.')+
      fig('character-options.jpg','J1 Classic Captain, J2 Deck Raider, J3 Treasure Corsair, J4 Storm Privateer front and rear')+
      `<div class="pirate-two"><div>${fig('hero-rear.png','Temporary J1 rear gameplay sprite','Separate rear-view compositing asset.')}</div><div><h2>What must read in play</h2><ul class="pirate-points"><li>Tricorn, broad shoulders and boar ears establish the silhouette.</li><li>Navy coat and ivory cuffs separate the body from the warm deck.</li><li>Gold edging and red cloth stay visible as large color areas.</li><li>Rear view: brass hook on viewer-left; wooden peg on viewer-right.</li><li>No bag, pouch, back cargo or carrying straps.</li></ul><p>The layout keeps the character large enough for these features to remain visible on a phone. Mobile QA uses the actual composed screen, not a full-size character board.</p>${note('Still to approve: final identity/outfit, gameplay silhouette and animation poses. Do not produce a final rig until the character lock.')}</div></div>`,
    environment:()=>head('04','A solid beginning. Open water ahead.','The harbor frames the route without becoming an obstacle to reading it.')+
      `<div class="section-heading"><h2>Updated environment</h2>${display}</div>${fig('harbor-dock.png','Updated N64 harbor with a broad fixed starting dock','The pier is visibly attached to the foreground shore. Its pilings and open front edge distinguish the start from floating targets.')}<div class="pirate-two">${fig('barrel.png','Sealed low-poly wooden barrel with a closed lid and blank multiplier plaque','Closed lid, bowed staves and two iron hoops: a barrel rather than an open tub or boat.')}<section><h2>Composition rules</h2><ul class="pirate-points"><li>Elevated rear camera; movement goes away from the viewer.</li><li>One centered route with visible water gaps.</li><li>Readable label sizes are protected from perspective shrinkage.</li><li>The next target stays ahead of the character.</li><li>Mobile removes peripheral scenery before shrinking the hero or controls.</li><li>Side-entry space is reserved for shark and tentacle effects.</li></ul></section></div>`,
    'final-ui':()=>head('05','The route and the decision, together.','Inspect the same game composition at desktop and phone sizes.')+screenMarkup('ready')+
      `<section><h2>Control hierarchy</h2>${table(['Element','Behavior'],[['Stake','Editable on the dock; locked once a round begins. The value is never silently changed.'],['GO ↑','One advance per activation. Disabled while a result resolves.'],['CASH OUT','Current total return in a stable location. Disabled before the first successful landing and after settlement.'],['Difficulty','Easy, Medium, Hard, Hardcore are retained from the references. Locked during a round. Production schedules remain unspecified.'],['GO MAX','Retained as a secondary reference control. It is inactive in this visual preview because its source behavior is not supplied.'],['Balance','Demo balance changes once per start or settlement. Production wallet integration is outside this art study.']])}</section>`+
      `<section><h2>Betting-bar references</h2><div class="pirate-two">${fig('betting-mobile-reference.jpg','Supplied mobile betting-bar reference','Mobile: stacked stake, actions, difficulty and balance.')}${fig('betting-desktop-reference.jpg','Supplied desktop betting-bar reference','Desktop: a compact console beneath the central play area.')}</div></section>`,
    states:()=>head('06','Every important state has a clear next action.','Select a state to inspect its artwork and controls. These are deterministic review examples.')+screenMarkup('active')+
      `<section><h2>State contract</h2>${table(['State','Visible response','Inspect'],states.map(s=>[s[1],s[2],`<button class="state-jump" data-state-pick="${s[0]}">Show state</button>`]))}</section>`+
      note('A failed target never receives a success tick or reward. Reconnection keeps the last confirmed value; it must not invent a result. Production replay and response reconciliation are backend integration requirements.'),
    animation:()=>head('07','One hop. Three comic failures.','The same failed advance can sink, be struck by a shark, or be interrupted by a tentacle.')+
      fig('barrel-losses.png','Three updated barrel loss performances with the temporary J1 boar','Loss concept sheet · J1 is temporary, all three share the same failed-step rule.')+
      table(['Sequence','Proposed timing','Purpose'],[['Idle / decision','Low-amplitude loop','Character breathes; barrels bob gently. No timing cue for a safe jump.'],['Advance','~650 ms','Anticipation → airborne arc → landing. Lock actions from request until resolved.'],['Safe landing','~200 ms settle','One short compression, then update current multiplier and cashout.'],['Cashout','~800 ms','Short celebration and stable receipt. Settle once.'],['Barrel sink','~900 ms','Tip and lower the attempted barrel; character follows into a splash.'],['Shark strike','~900 ms','Strong side-entry silhouette and a single readable comic impact.'],['Tentacle grab','~1,000 ms','One open coil gathers around the body, then pulls toward the sea.'],['Reset','~400 ms','Return to the fixed dock and unlock stake/difficulty.']])+
      `<section><h2>Production handoff</h2><p>Separate hat, head, torso/coat tails, left hook arm, right hand arm, natural leg, peg leg and tail. Reconstruct hidden overlaps before rigging. Keep barrel, plaque, waterline and each effect independent. Labels remain live UI text.</p><p>The website uses transforms of raster assets to preview the sequence. A continuous Spine rig, authored key poses and final effect timing remain production work. Reduced motion uses short state changes rather than large travel or camera movement.</p></section>`,
    production:()=>head('08','A 15-working-day art plan.','Parallel effort across UI, 2D art and Spine; estimates start after character and source-rule decisions.')+
      `<section id="milestones"><h2>Milestones</h2>${table(['Window','Milestone','Acceptance'],[['Days 1–2','Visual and interaction lock','Select character/outfit. Approve rear silhouette, barrel route, start dock and mobile betting panel. Confirm source rules.'],['Days 3–5','Production assets and UI kit','Named separated assets, reconstructed overlaps, final type/color tokens, all button states.'],['Days 6–10','Motion and integration','Idle, hop, landing, cashout, three loss variants and reset; event-driven UI integration.'],['Days 11–13','Device and state QA','360/390/430 px phone views, desktop, reduced motion, errors, reconnecting and label visibility.'],['Days 14–15','Review buffer and submission','Fix review findings; native Figma presentation, matching PDF and verified source handoff.']])}</section>`+
      `<section id="workload"><h2>Workload by role</h2>${table(['Role','Task decomposition','Estimated effort'],[['UI Designer','Layouts 2d; component kit 2d; states 1.5d; mobile QA 1.5d; export/handoff 1d.','8 person-days'],['2D Artist','Character/style lock 2d; environment 2d; barrels and effects 2d; key poses 2d; layer cleanup/polish 2d.','10 person-days'],['2D Spine Animator','Rig preparation 1d; idle/hop 2d; landing/cashout 1d; losses 3d; integration 1d.','8 person-days'],['Art Lead','Reviews at each milestone, task acceptance and scope decisions, spread across the schedule.','~3 person-days, overlapping']])}<p>26 production person-days run in parallel across three specialists; this is not 26 elapsed days. The 15-day window includes integration checks and a two-day correction buffer. Engineering, game-math approval and certification are separate dependencies.</p></section>`+
      `<section id="risks"><h2>Risks and mitigations</h2>${table(['Risk','Mitigation','Owner'],[['Character changes after rigging','Lock silhouette/outfit before final layers and rig. Use J1 only for the present layout study.','Art Lead + 2D'],['Multipliers shrink or overlap','Minimum label size, near-camera staging and independent live values. Review 360 px early.','UI'],['Style drifts across assets','One N64 reference board; broad shading/material checks at every handoff.','Art Lead'],['Effects obscure decisions','Keep readouts independent; localize effects to the failed target.','UI + Spine'],['Unclear original rules','Confirm full schedules, stake limits, difficulty, settlement and GO MAX before gameplay integration.','Product + Engineering'],['Rig or export mismatch','Agree pivots, layer names, timing events and engine versions before rigging. Test an early vertical slice.','Spine + Engineering']])}</section>`,
    deliverables:()=>head('09','Review material now. Final assembly after approval.','The website is the review workspace; it does not replace the required Figma file and matching presentation PDF.')+
      `<div class="delivery-links"><a href="https://app.notion.com/p/3e149f0e94c881758610d7dea2078962" target="_blank" rel="noopener"><strong>Notion design brief ↗</strong><span>Decisions, authority, controls, states and production plan.</span></a><a href="/game-art-review/instant/play/" target="_blank" rel="noopener"><strong>Responsive gameplay study ↗</strong><span>Barrels, fixed dock, live labels and state previews.</span></a><a href="${A}assignment-brief.pdf" target="_blank" rel="noopener"><strong>Original assignment ↗</strong><span>The supplied source requirements.</span></a></div>`+
      table(['Deliverable','Current status'],[['Six supplied references','Preserved in their original image order and available in the relevant review sections.'],['Updated environment / barrel / temporary hero','Separate PNG assets available below.'],['Desktop and mobile','Responsive implementation based on the 12ui exports, available for review.'],['Gameplay and loss states','Interactive raster preview plus updated loss concept sheet.'],['Production plan','Role estimates, milestones, dependencies and risks proposed.'],['Final character / wardrobe','Pending user approval. J1 is temporary.'],['Native Figma file and matching PDF','Pending final visual approval and presentation assembly. No Figma link or final PDF is claimed.'],['Production rig / game mathematics','Not supplied by this visual study.']])+
      `<section><h2>Separate assets</h2><div class="delivery-links">${[['harbor-dock.png','Harbor & fixed dock'],['barrel.png','Barrel target'],['hero-rear.png','J1 rear sprite'],['barrel-losses.png','Loss concepts'],['shark.png','Shark effect'],['tentacle.png','Tentacle effect']].map(r=>`<a href="${A+r[0]}" download><strong>${r[1]} ↗</strong><span>PNG image</span></a>`).join('')}</div></section>`
  };
  content.innerHTML=(pages[active]||pages.brief)();
  wireDisplay();
  wireScreen(content);
}

function screenMarkup(initial){
  return `<div class="pirate-review-controls"><div class="segmented" role="group" aria-label="Preview device"><button data-device="desktop" aria-pressed="true">Desktop</button><button data-device="mobile" aria-pressed="false">Mobile</button></div><label>State <select id="pirate-state">${states.map(s=>`<option value="${s[0]}" ${initial===s[0]?'selected':''}>${s[1]}</option>`).join('')}</select></label><label class="mobile-width-control" hidden>Phone width <select id="pirate-width"><option>360</option><option selected>390</option><option>430</option></select></label><button id="pirate-reset">Reset preview</button><a href="/game-art-review/instant/play/" target="_blank" rel="noopener">Open full view ↗</a></div><div class="pirate-preview-shell"><div class="pirate-frame-holder"><iframe title="Pirate Sea Hop gameplay study" src="/game-art-review/instant/play/?state=${initial}"></iframe></div></div><p class="caption">Scripted art preview · no real wagers. GO advances through the supplied sample values. State selection shows each outcome directly. J1 remains a temporary character.</p>`;
}
function wireScreen(content){
 const frame=content.querySelector('iframe');if(!frame)return;
 const holder=content.querySelector('.pirate-frame-holder'),shell=content.querySelector('.pirate-preview-shell');
 let device=innerWidth<600?'mobile':'desktop',phone=390;
 const resize=()=>{const w=device==='mobile'?phone:1440,h=device==='mobile'?844:900,scale=Math.min(1,(shell.clientWidth-16)/w);frame.style.width=w+'px';frame.style.height=h+'px';frame.style.transform=`scale(${scale})`;holder.style.width=w*scale+'px';holder.style.height=h*scale+'px';content.querySelectorAll('[data-device]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.device===device)));content.querySelector('.mobile-width-control').hidden=device!=='mobile';};
 content.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;resize()});
 content.querySelector('#pirate-width').onchange=e=>{phone=+e.target.value;resize()};
 const show=s=>{content.querySelector('#pirate-state').value=s;frame.contentWindow?.postMessage({type:'pirate-review-state',state:s},location.origin)};
 content.querySelector('#pirate-state').onchange=e=>show(e.target.value);
 content.querySelector('#pirate-reset').onclick=()=>show('ready');
 content.querySelectorAll('[data-state-pick]').forEach(b=>b.onclick=()=>{show(b.dataset.statePick);shell.scrollIntoView({behavior:'smooth',block:'start'})});
 frame.onload=()=>{resize();show(content.querySelector('#pirate-state').value)};new ResizeObserver(resize).observe(shell);resize();
}
