const A='/game-art-review/assets/instant-final/';
const H=s=>'/game-art-review/instant/?section='+s;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const fig=(file,title,caption='')=>`<figure class="pirate-figure"><a href="${A+file}" target="_blank" rel="noopener"><img data-study src="${A+file}" alt="${esc(title)}" loading="lazy"></a><figcaption><strong>${esc(title)}</strong>${caption?`<br>${esc(caption)}`:''}</figcaption></figure>`;
const table=(heads,rows)=>`<div class="pirate-table"><table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const note=t=>`<aside class="pirate-note">${t}</aside>`;
const download=(file,title,detail)=>`<a href="${A}downloads/${file}" download><strong>${title} ↓</strong><span>${detail}</span></a>`;
const screen=(device,i)=>`screens/${device}-${String(i+1).padStart(2,'0')}.webp`;
export async function renderInstant({content,active,heading,wireDisplay}){
 document.body.classList.add('pirate-review');
 if(!document.querySelector('#instant-style')){const l=document.createElement('link');l.id='instant-style';l.rel='stylesheet';l.href='/game-art-review/instant-review.css?v=20260921-environment-v1';document.head.append(l);}
 const response=await fetch(A+'manifest.json?v=20260921-refs9');if(!response.ok)throw new Error('Instant artwork could not load');const m=await response.json();
 const head=(n,t,d)=>heading(n+' / INSTANT GAME',t,d);
 const display='<div class="segmented" role="group" aria-label="Art display"><button data-display="color" aria-pressed="true">Color</button><button data-display="grayscale" aria-pressed="false">Grayscale</button></div>';
 const gallery=category=>`<div class="instant-asset-grid">${m.assets.filter(a=>!category||a.category===category).map(a=>fig('art/'+a.file,a.title)).join('')}</div>`;
 const view=()=>`<div class="pirate-review-controls"><div class="segmented" role="group" aria-label="Preview device"><button data-device="desktop" aria-pressed="true">Desktop</button><button data-device="mobile" aria-pressed="false">Mobile</button></div><label>Screen <select id="instant-state">${m.states.map((s,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} · ${s}</option>`).join('')}</select></label>${display}</div><div id="instant-screen" aria-live="polite"></div><p class="caption">Original artwork from your desktop and mobile PDF exports, in left-to-right order. Open any screen to inspect it at full size.</p>`;
 const phases=[['Ready to bet','Stake presets and Easy / Medium / Hard / Hardcore selection. BET begins the round.'],['First jump','The pirate leaves the ship deck and moves toward the first crate.'],['First safe landing','The pirate reaches the crate; JUMP and CASHOUT become the decision controls.'],['Route advances','The composition follows the pirate, keeping the next target above the current platform.'],['Barrel landing','The route changes from crates to barrels with the pirate grounded on the landing surface.'],['Next jump','The pirate advances again; the next target remains visible.'],['Tentacle encounter','A purple tentacle coils around the pirate.'],['Shark encounter','A shark interrupts the route with a clear character reaction.'],['Mermaid encounter','A mermaid encounter provides a distinct comic character pose.'],['Cashout result','A YOU WIN panel displays the example result of $246.']];
 const milestones=[['Days 1–2','Direction & layout lock','Approve route, phone hierarchy, silhouette, materials and rig feasibility.'],['Days 3–5','Assets & component kit','Named layers, editable UI states and a working rig with one test jump.'],['Days 6–10','Motion & integration','Connect idle, jump, landing, encounters, cashout and reset.'],['Days 11–13','Device & state QA','360/390/430 px phones, desktop, contrast, reduced motion and reconnect.'],['Days 14–15','Correction buffer & handoff','Resolve findings, verify exports and review the Figma/PDF submission.']];
 const workload=[['UI Designer','Layouts 2d; component kit 2d; states 1.5d; device/accessibility QA 1.5d; handoff 1d.','8 person-days'],['2D Artist','Asset audit 1d; character layers 3d; environment 2d; encounter layers 2d; cleanup 2d.','10 person-days'],['2D Spine Animator','Rig 2d; idle/jump/landing 2d; encounters 2d; cashout/reset 1d; integration 1d.','8 person-days'],['Art Lead','Direction, scope, milestone reviews, risk decisions and submission checks.','3 person-days, overlapping']];
 const risks=[['Busy water','Review grayscale and phone-scale contrast; protect outlines and stable readouts.','UI + Art Lead'],['Flat PNG assets','Separate limbs and effects; reconstruct hidden overlaps before rigging.','2D + Animator'],['Landing mismatch','Share ground pivots and camera direction; approve one jump before all variants.','Animator + Engineering'],['Payout mismatch','Use authoritative round values, consistent decimals and single settlement.','UI + Engineering'],['Water seams & visual clutter','Verify water tiling and keep encounter effects away from readable values.','2D + Animator'],['Scope creep','Freeze direction, use milestone gates and protect the two-day correction buffer.','Art Lead']];
 const characters=active==='character-concept'?await import('/game-art-review/instant-characters.js?v=20260921-boards4'):null;
 const environmentExtraFiles=['8DE0DFBE-D82A-4782-AB74-D2524A0C4BA6.webp','F982C7ED-7785-4E4F-85E4-7C7DF54AD07F.webp','419855C5-4950-46AC-8252-38AEF175F3D4.webp'];
 const mainEnvironment=()=>fig('art/environment-overview.png','Main environment · complete route','Full composition, from the starting ship to the treasure island.').replace('class="pirate-figure"','class="pirate-figure instant-environment-hero"').replace('loading="lazy"','loading="eager" fetchpriority="high" width="375" height="1818"');
 const environmentGallery=()=>`<div class="instant-asset-grid" aria-label="Environment assets">${[...m.assets.filter(a=>a.category==='environment'&&!environmentExtraFiles.includes(a.file)),...environmentExtraFiles.map(file=>m.assets.find(a=>a.file===file))].filter(Boolean).map(a=>fig('art/'+a.file,a.title)).join('')}</div>`;
 const motionGallery=()=>`<div class="instant-asset-grid">${m.assets.filter(a=>a.category==='hazard').map(a=>fig('art/'+a.file,a.title)).join('')}${fig('art/shark-fin-motion.png','Shark fin')}</div>`;
 const pages={
 brief:()=>head('01','One more jump. Or take the treasure.','Pirate Sea Hop — a pirate crossing with a clear advance-or-cashout decision.')+fig(screen('desktop',0),'Main game screen','Supplied desktop artwork.')+table(['Topic','Direction'],[
 ['Idea & theme','A pirate crosses turquoise water by jumping between floating crates and barrels. Every safe landing creates a new choice: advance or collect the current return.'],
 ['Intended audience','Adults of legal gambling age who prefer short instant-game sessions. This is a planning hypothesis, not a validated research finding.'],
 ['Visual style','Polished, stylized 3D game art: oversized readable forms, warm sculpted wood, gold trim, saturated turquoise water and a recognizable pirate silhouette.'],
 ['Visual differentiation','A visible route makes progress easy to follow. The rear-view pirate, map and comic sea encounters give the game its identity without steering or combat.'],
 ['Decision hierarchy','Hero and next target first; current multiplier and cashout second; scenery supports the crossing.'],
 ['Controls','Choose stake and difficulty. BET begins play; JUMP continues after a safe landing; CASHOUT collects the confirmed return.']])+`<section><h2>The round</h2><ol class="pirate-flow"><li>Choose stake and difficulty on the starting ship deck.</li><li>BET requests the first jump.</li><li>A safe landing advances the route and updates the current return.</li><li>Choose JUMP again or CASHOUT.</li><li>An unsuccessful advance ends the uncashed round; cashout shows the result.</li></ol></section><nav class="board-jumps"><a href="${H('final-ui')}">Desktop & mobile</a><a href="${H('production')}">Production plan</a><a href="${H('deliverables')}">Presentation & sources</a></nav>`,
 'art-direction':()=>head('02','Readable forms. Shared materials.','The supplied references and finished artwork define the visual direction.')+`<section><h2>Reference moodboard</h2><p>${m.references.length} selected references in the approved order. Reference authorship is not claimed.</p><div class="instant-asset-grid">${m.references.map((r,i)=>fig('references/'+r.file,`Reference ${String(i+1).padStart(2,'0')}`,r.source)).join('')}</div></section><section><h2>Visual principles</h2>${table(['Principle','Application'],[['Silhouette first','Oversized tricorn, red scarf and hook identify the pirate; broad crate and barrel tops define landing surfaces.'],['Material consistency','Match sculpted wood, broad bevels, gold trim, metal highlights, lighting and foam across props.'],['Hierarchy','Turquoise water is the field, warm wood describes the route, and navy supports the control panel. Green marks BET/JUMP; yellow highlights CASHOUT.'],['Type & mobile clarity','Preserve bold white multipliers with dark outlines. Use editable text in production and verify the exact font in the source design.'],['Depth','Shared elevated camera, grounding shadows and consistent water contact keep the objects in one world.']])}</section>${display}${fig(screen('desktop',4),'Art direction in context')}`,
 'character-concept':()=>characters.renderCharacterBoards(heading),
 environment:()=>head('04','A solid start. A clear route ahead.','The ship deck anchors the opening; crates and barrels carry the route through turquoise water.')+mainEnvironment()+environmentGallery()+`<section><h2>Composition rules</h2><ul class="pirate-points"><li>Keep the hero and next landing target on the centerline.</li><li>Use water gaps and consistent contact shadows to separate floating targets.</li><li>Reserve the sides for wreckage, fins and encounters.</li><li>Protect multiplier readability over bright foam.</li><li>On mobile, preserve the character and controls before peripheral scenery.</li><li>Check water seams in the engine before using repeating tiles.</li></ul></section>`,
 'final-ui':()=>head('05','Desktop and mobile, in the finished artwork.','Ten corresponding views per device, taken directly from the supplied PDF exports.')+view()+`<section><h2>Control hierarchy</h2>${table(['Element','Intended behavior'],[['Stake & presets','Editable before the round; keep the chosen amount visible during play.'],['Difficulty','Easy, Medium, Hard and Hardcore. Confirm schedules with the game specification.'],['BET / JUMP','One request per activation. Lock repeated input while the outcome resolves.'],['CASHOUT','Show the confirmed total return; settle once and retain a clear receipt.'],['Balance','Stable placement independent of character and encounter animation.']])}</section><div class="delivery-links">${download('Instant_Web.pdf','Original desktop PDF','Unchanged Figma export')}${download('Instant_Mobile.pdf','Original mobile PDF','Unchanged Figma export')}</div>`,
 states:()=>head('06','Every step of the crossing.','Inspect the ten supplied visual states at desktop and mobile sizes.')+view()+table(['Screen','Visible response','Inspect'],phases.map((p,i)=>[`${String(i+1).padStart(2,'0')} · ${p[0]}`,p[1],`<button class="state-jump" data-state-pick="${i}">Show state</button>`]))+`<section><h2>Runtime state contract</h2>${table(['State','Production requirement'],[['Ready','Stake and difficulty editable; no cashout before a successful landing.'],['Resolving','Lock round actions while an advance or cashout is pending.'],['Active','Update multiplier and cashout together after confirmed success.'],['Settled / lost','Settle cashout once; a loss ends the uncashed round. Reset only after the outcome is acknowledged.'],['Errors / reconnect','Keep the last confirmed round state and show an inline reason when an action is unavailable. These error screens are not part of the supplied artwork.']])}</section>`+note('The exports contain illustrative values, mixed decimal separators and repeated cashout amounts. Artwork is preserved exactly; production values must be reconciled with the game rules. The $246 win is an example result.'),
 animation:()=>head('07','Distinct encounters. One motion language.','The supplied poses define the visual targets; the timings below are production proposals.')+motionGallery()+`<div class="pirate-two">${fig('art/DF70CFF3-41E1-436F-A3B7-CD210B5A7C4E.webp','Shark encounter pose')}${fig('art/17FC7B14-020B-4501-AC7E-A98463E068A9.webp','Mermaid encounter pose')}</div>`+table(['Sequence','Proposed timing','Purpose'],[['Idle','Low-amplitude loop','Breathing and gentle platform movement; no timing cue for a safe jump.'],['Jump','550–700 ms','Anticipation, readable airborne arc and grounded contact.'],['Landing','150–250 ms','Brief compression and return to the decision pose.'],['Encounters','800–1,100 ms','Distinct tentacle, shark and mermaid silhouettes; keep the result readable.'],['Cashout','600–900 ms','Short celebration followed by a stable result.'],['Reset','300–450 ms','Return to the deck and unlock pre-round controls.']])+`<section><h2>Animation handoff</h2><p>Separate character and effect parts, reconstruct hidden overlaps and share a ground pivot. Use takeoff, contact, impact and completion events. Server results control settlement; motion does not award money.</p><p>Reduced motion uses short pose changes. No completed Spine rig or animation export is included in the supplied files.</p></section>`,
 production:()=>head('08','15 working days, with parallel specialists.','A production plan for turning the supplied direction into an integrated game.')+`<section><h2>Milestones & acceptance</h2>${table(['Window','Milestone','Acceptance'],milestones)}</section><section><h2>Workload by role</h2>${table(['Role','Task decomposition','Estimate'],workload)}<p>26 production person-days across three specialists, plus 3 overlapping Art Lead days. These run in parallel within the 15-day schedule. Engineering, game mathematics, audio and certification are separate dependencies.</p></section><section><h2>Risks & mitigations</h2>${table(['Risk','Response','Owner'],risks)}</section><section><h2>Review discipline</h2><p>Approve one representative asset and one complete jump before producing all variants. Review each milestone at desktop and actual phone size. Track owners, dependencies and acceptance criteria; reserve the final two days for corrections and handoff.</p></section>`,
 deliverables:()=>head('09','The Instant game review package.','Presentation, original screen exports, source assets, references and the supplied Figma link.')+`<section id="figma" class="submission-card"><span class="status">Link supplied</span><h2>Figma design</h2><p>Open the Instant game source design.</p><div class="preview-actions"><a class="link-button primary" href="${esc(m.figma)}" target="_blank" rel="noopener noreferrer">Open Instant game in Figma ↗</a><button id="copy-figma" class="link-button" type="button">Copy Figma link</button></div><p id="copy-status" role="status"></p><input id="figma-url" aria-label="Figma link" type="text" readonly value="${esc(m.figma)}" hidden></section><div class="delivery-links">${download('Pirate_Sea_Hop_Test_Presentation.pdf','Instant game presentation','23 pages · concept, artwork, states and production plan')}${download('Instant_Web.pdf','Desktop screen export','Original PDF · 10 views')}${download('Instant_Mobile.pdf','Mobile screen export','Original PDF · 10 views')}${download('Instant_Game_Assets.zip','Game assets','21 original PNG assets')}${download('Instant_References.zip','Reference pack','15 supplied reference images')}${download('Assignment_Brief.pdf','Test assignment','Original requirements')}</div>`+table(['Deliverable','Included'],[['Concept & art direction','Game idea, theme, intended audience, visual principles and reference moodboard.'],['Character & environment','21 asset previews and unchanged original PNGs in the ZIP.'],['Desktop & mobile','All 20 screen views, with an interactive device/state selector.'],['Presentation','23-page review presentation covering artwork and production leadership.'],['Production plan','Task decomposition, milestone gates, role estimates, risks and mitigations.'],['Figma','Author-supplied link; no changes made to the Figma document.'],['Runtime production','Layer separation, Spine rigs, integrated errors and game mathematics remain production tasks.']])+`<section><h2>Asset inventory</h2>${gallery()}</section>`
 };
 content.innerHTML=(pages[active]||pages.brief)();
 if(characters)characters.wireCharacterBoards(content);
 let device=innerWidth<600?'mobile':'desktop',index=0;
 const show=()=>{const el=content.querySelector('#instant-screen');if(!el)return;el.className='instant-screen '+device;el.innerHTML=fig(screen(device,index),`${device==='desktop'?'Desktop':'Mobile'} · ${String(index+1).padStart(2,'0')} · ${m.states[index]}`);content.querySelectorAll('[data-device]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.device===device)));content.querySelector('#instant-state').value=String(index);wireDisplay();};
 content.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;show();});
 const select=content.querySelector('#instant-state');if(select)select.onchange=()=>{index=Number(select.value);show();};
 content.querySelectorAll('[data-state-pick]').forEach(b=>b.onclick=()=>{index=Number(b.dataset.statePick);show();content.querySelector('.pirate-review-controls').scrollIntoView({block:'start'});});
 const copy=content.querySelector('#copy-figma');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(m.figma);content.querySelector('#copy-status').textContent='Figma link copied.';}catch{const input=content.querySelector('#figma-url');input.hidden=false;input.select();content.querySelector('#copy-status').textContent='Select and copy the link above.';}};
 show();wireDisplay();
}
